### ISSUE TITLE
Converter for recipe submission

### ISSUE THREAD

**Issue by cjthedj97** [cjthedj97/chowdown#55]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by DrSpaldo** [comment]
Hi @cjthedj97, do you have your converter source available for someone to use? I made my [own one](https://cc.spaldo.net/) but I think yours is a little nicer.

**Comment by cjthedj97** [comment]
the code for for the most part is inline code in the convert.md file
